import { bootstrapApplication } from '@angular/platform-browser';
import { provideAnimations } from '@angular/platform-browser/animations';
import { provideHttpClient } from '@angular/common/http';
import { provideRouter, withInMemoryScrolling } from '@angular/router';
import { provideTranslateService } from '@ngx-translate/core';
import { provideTranslateHttpLoader } from '@ngx-translate/http-loader';
import {
  LucideAccessibility,
  LucideAppWindow,
  LucideArrowRight,
  LucideArrowUp,
  LucideAtom,
  LucideBadge,
  LucideBlocks,
  LucideBot,
  LucideBraces,
  LucideChartColumn,
  LucideChevronDown,
  LucideCheckCheck,
  LucideCheckCircle2,
  LucideCloud,
  LucideCode2,
  LucideCoffee,
  LucideComponent,
  LucideContainer,
  LucideCookie,
  LucideDatabase,
  LucideDatabaseZap,
  LucideExternalLink,
  LucideFileCode,
  LucideFileCode2,
  LucideFlaskConical,
  LucideGitBranch,
  LucideGlobe,
  LucideKeyRound,
  LucideLayers3,
  LucideMail,
  LucideMenu,
  LucideMonitorSmartphone,
  LucideMoon,
  LucidePaintbrush,
  LucidePalette,
  LucidePanelTop,
  LucideRadioTower,
  LucideRoute,
  LucideRouter,
  LucideRocket,
  LucideSend,
  LucideServerCog,
  LucideShieldCheck,
  LucideSparkles,
  LucideSquareCode,
  LucideSun,
  LucideTerminal,
  LucideTerminalSquare,
  LucideTestTube2,
  LucideTrainTrack,
  LucideTriangle,
  LucideWorkflow,
  LucideX,
  provideLucideIcons,
} from '@lucide/angular';

import { AppComponent } from './app/app.component';
import { routes } from './app/app.routes';

bootstrapApplication(AppComponent, {
  providers: [
    provideHttpClient(),
    provideAnimations(),
    provideTranslateService({
      fallbackLang: 'es',
      lang: 'es',
      loader: provideTranslateHttpLoader({
        prefix: 'assets/i18n/',
        suffix: '.json',
      }),
    }),
    provideLucideIcons(
      LucideAccessibility,
      LucideAppWindow,
      LucideArrowRight,
      LucideArrowUp,
      LucideAtom,
      LucideBadge,
      LucideBlocks,
      LucideBot,
      LucideBraces,
      LucideChartColumn,
      LucideChevronDown,
      LucideCheckCheck,
      LucideCheckCircle2,
      LucideCloud,
      LucideCode2,
      LucideCoffee,
      LucideComponent,
      LucideContainer,
      LucideCookie,
      LucideDatabase,
      LucideDatabaseZap,
      LucideExternalLink,
      LucideFileCode,
      LucideFileCode2,
      LucideFlaskConical,
      LucideGitBranch,
      LucideGlobe,
      LucideKeyRound,
      LucideLayers3,
      LucideMail,
      LucideMenu,
      LucideMonitorSmartphone,
      LucideMoon,
      LucidePaintbrush,
      LucidePalette,
      LucidePanelTop,
      LucideRadioTower,
      LucideRoute,
      LucideRouter,
      LucideRocket,
      LucideSend,
      LucideServerCog,
      LucideShieldCheck,
      LucideSparkles,
      LucideSquareCode,
      LucideSun,
      LucideTerminal,
      LucideTerminalSquare,
      LucideTestTube2,
      LucideTrainTrack,
      LucideTriangle,
      LucideWorkflow,
      LucideX,
    ),
    provideRouter(
      routes,
      withInMemoryScrolling({
        anchorScrolling: 'enabled',
        scrollPositionRestoration: 'enabled',
      }),
    ),
  ],
}).catch((error) => console.error(error));
